import { Search, ShoppingBag } from "lucide-react";
import { useMemo, useState } from "react";
import { updateAdminStoreOrder, type AdminData, type StoreOrderStatus } from "../../api";
import { AdminModal, DataTable, Panel, StatusBadge } from "../../components/admin-ui";
import { adminMoney } from "../../utils/format";

const labels: Record<StoreOrderStatus, string> = { pending: "New", confirmed: "Confirmed", processing: "Processing", shipped: "Shipped", completed: "Completed", cancelled: "Cancelled" };
const nextStatuses: Record<StoreOrderStatus, StoreOrderStatus[]> = { pending: ["confirmed", "cancelled"], confirmed: ["processing", "cancelled"], processing: ["shipped", "cancelled"], shipped: ["completed"], completed: [], cancelled: [] };
const paymentLabels: Record<string, string> = { pending: "Payment pending", paid: "Paid", failed: "Payment failed", refunded: "Refunded" };

export function StoreOrdersSection({ orders, runAction }: { orders: AdminData["storeOrders"]; runAction: (action: () => Promise<unknown>) => Promise<void> }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"all" | StoreOrderStatus>("all");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const selected = orders.find((order) => order.id === selectedId) ?? null;
  const filtered = useMemo(() => orders.filter((order) => {
    const search = `${order.id} ${order.customer.firstName} ${order.customer.lastName} ${order.customer.phone} ${order.items.map((item) => item.productName).join(" ")}`.toLowerCase();
    return (status === "all" || order.status === status) && search.includes(query.trim().toLowerCase());
  }), [orders, query, status]);

  return <div className="admin-grid"><Panel title="Store orders" wide><div className="inventory-summary-grid"><article><span>All orders</span><strong>{orders.length}</strong><small>{orders.filter((order) => order.status === "pending").length} require attention</small></article><article><span>Paid</span><strong>{orders.filter((order) => order.paymentStatus === "paid").length}</strong><small>Confirmed by payment provider</small></article><article><span>In progress</span><strong>{orders.filter((order) => ["confirmed", "processing", "shipped"].includes(order.status)).length}</strong><small>Confirmed and fulfilment</small></article><article><span>Order value</span><strong>{adminMoney.format(orders.filter((order) => order.status !== "cancelled").reduce((sum, order) => sum + order.totalAmount, 0))}</strong><small>Excluding cancelled</small></article></div><div className="table-toolbar"><label><span>Search</span><div className="admin-search table-search"><Search size={17} /><input placeholder="Order, client, phone, product" value={query} onChange={(event) => setQuery(event.target.value)} /></div></label><label><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="all">All statuses</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><DataTable columns={["Order", "Date", "Customer", "Items", "Delivery", "Total", "Payment", "Status", "Actions"]} rows={filtered.length ? filtered.map((order) => [<button className="table-link-button" onClick={() => setSelectedId(order.id)}>#{order.id}</button>, new Date(order.createdAt).toLocaleString("en-GB"), `${order.customer.firstName} ${order.customer.lastName}\n${order.customer.phone}`, order.items.map((item) => `${item.productName} × ${item.quantity}`).join(", "), order.deliveryMethod === "pickup" ? "Pickup" : order.deliveryAddress || "Delivery", adminMoney.format(order.totalAmount), <StatusBadge status={order.paymentStatus} />, <StatusBadge status={order.status} />, <button className="secondary-button compact-button" onClick={() => setSelectedId(order.id)}>Details</button>]) : [["No matching orders", "-", "-", "-", "-", "-", "-", "-", "-"]]} /></Panel>
    {selected ? <AdminModal title={`Store order #${selected.id}`} onClose={() => setSelectedId(null)}><div className="store-order-details"><div className="store-order-detail-head"><span><StatusBadge status={selected.status} /> <StatusBadge status={selected.paymentStatus} /></span><span>{new Date(selected.createdAt).toLocaleString("en-GB")}</span></div><dl className="info-list"><div><dt>Customer</dt><dd>{selected.customer.firstName} {selected.customer.lastName}</dd></div><div><dt>Phone</dt><dd>{selected.customer.phone}</dd></div><div><dt>Email</dt><dd>{selected.customer.email || "-"}</dd></div><div><dt>Delivery</dt><dd>{selected.deliveryMethod === "pickup" ? "Pickup from salon" : selected.deliveryAddress || "Delivery"}</dd></div><div><dt>Payment</dt><dd>{paymentLabels[selected.paymentStatus] ?? selected.paymentStatus}{selected.paidAt ? ` · ${new Date(selected.paidAt).toLocaleString("en-GB")}` : ""}</dd></div><div><dt>Invoice</dt><dd>{selected.monobankInvoiceId || "-"}</dd></div><div><dt>Payment issue</dt><dd>{selected.paymentError || "-"}</dd></div><div><dt>Comment</dt><dd>{selected.comment || "-"}</dd></div></dl><div className="store-order-items"><h3>Products</h3>{selected.items.map((item) => <div key={item.id}><span><ShoppingBag size={15} /> {item.productName} × {item.quantity}</span><strong>{adminMoney.format(item.unitPrice * item.quantity)}</strong></div>)}<div><strong>Total</strong><strong>{adminMoney.format(selected.totalAmount)}</strong></div></div><div className="store-order-stock"><span>Stock deducted: {selected.stockDeductedAt ? new Date(selected.stockDeductedAt).toLocaleString("en-GB") : "no"}</span><span>Stock restored: {selected.stockRestoredAt ? new Date(selected.stockRestoredAt).toLocaleString("en-GB") : "no"}</span></div>{nextStatuses[selected.status].length ? <div className="modal-actions">{nextStatuses[selected.status].map((next) => <button className={next === "cancelled" ? "secondary-button" : "primary-button"} key={next} onClick={() => void runAction(async () => { await updateAdminStoreOrder(selected.id, next); setSelectedId(null); })}>{labels[next]}</button>)}</div> : null}</div></AdminModal> : null}
  </div>;
}
